### ISSUE TITLE
Less parser on PHP 8.2

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/Less#3]
38×	
PHP Deprecated: Creation of dynamic property Less_Tree_Variable::$parensInOp is deprecated in ...\modules\Less\wikimedia\less.php\lib\Less\Parser.php:2351
30×	
PHP Deprecated: Creation of dynamic property Less_Tree_Dimension::$parensInOp is deprecated in ...\modules\Less\wikimedia\less.php\lib\Less\Parser.php:2352
82×	
PHP Deprecated: Creation of dynamic property Less_Tree_Variable::$parensInOp is deprecated in ...\modules\Less\wikimedia\less.php\lib\Less\Parser.php:2313
86×	
PHP Deprecated: Creation of dynamic property Less_Tree_Dimension::$parensInOp is deprecated in ...\modules\Less\wikimedia\less.php\lib\Less\Parser.php:2314
92×	
PHP Deprecated: Creation of dynamic property Less_Tree_Variable::$parensInOp is deprecated in ...\modules\Less\wikimedia\less.php\lib\Less\Parser.php:2430
1×	
PHP Deprecated: Creation of dynamic property Less_Tree_Call::$parensInOp is deprecated in ...\modules\Less\wikimedia\less.php\lib\Less\Parser.php:2313
9×	
PHP Deprecated: Creation of dynamic property Less_Tree_Variable::$parensInOp is deprecated in ...\modules\Less\wikimedia\less.php\lib\Less\Parser.php:2352
4×	
PHP Deprecated: Creation of dynamic property Less_Tree_Dimension::$parensInOp is deprecated in ...\modules\Less\wikimedia\less.php\lib\Less\Parser.php:2313
4×	
PHP Deprecated: Creation of dynamic property Less_Tree_Variable::$parensInOp is deprecated in ...\modules\Less\wikimedia\less.php\lib\Less\Parser.php:2314
6×	
PHP Deprecated: Creation of dynamic property Less_Tree_Negative::$parensInOp is deprecated in ...\modules\Less\wikimedia\less.php\lib\Less\Parser.php:2351
27×	
PHP Deprecated: Creation of dynamic property Less_Tree_Directive::$allExtends is deprecated in ...\wikimedia\less.php\lib\Less\Visitor\extendFinder.php:102
107×	
PHP Deprecated: Creation of dynamic property Less_Tree_Media::$allExtends is deprecated in ...\wikimedia\less.php\lib\Less\Visitor\extendFinder.php:93

**Comment by adrianbj** [comment]
@ryancramerdesign - any chance you could update the wikimedia library please? I have done it locally and the current version fixes all the PHP 8.2 issues so it should be a really quick fix for you. Thanks.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign Thanks!
